global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090','localhost:9100']

  - job_name: 'second_node'
    scrape_interval: 5s
    static_configs:
      - targets: ['107.21.68.149:9100']
    
